# syntax=docker/dockerfile:1
FROM public.ecr.aws/docker/library/golang as builder
WORKDIR /src/hypatia
ENV GOPROXY direct
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY *.go .
COPY cmd cmd
RUN go test -race -timeout 120s ./...